# Generated by Django 3.1.4 on 2021-01-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KZ', 'Kozhikode'), ('MA', 'Malappuram'), ('WA', 'Wayanad'), ('TS', 'Thrissur'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KT', 'Kottayam'), ('AL', 'Alappuzha'), ('TV', 'Thiruvananthapuram'), ('KL', 'Kollam'), ('PL', 'Palakkad'), ('PT', 'Pathanamthitta')], max_length=20),
        ),
    ]
