# Generated by Django 3.1.4 on 2021-01-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='submitted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
