# Generated by Django 3.1.4 on 2021-01-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
